README.md, docs/community-and-support.md, docs/compute.md, docs/permissions.md, docs/python-client-examples.md, docs/quickstart.md, docs/retrieve-secret.md, docs/store-secrets.md, docs/technical-reports-and-demos.md, docusaurus.config.js, sidebars.js
as part of the transfer of repositories over to the NillionNetwork GitHub org, these changes reflect the URL updates. there are already redirects in place, however it's best to align with the updated URLs.
=> chore: update repo URL references to reflect transfer

docs/_sdk-installation.mdx, docs/nilup.md
This commit changes the URL used to instruct users to install nilup to include the /install.sh path. Even though the root path (/) is essentially an alias for /install.sh, we shouldn't lock ourselves into that forever being the case.
=> chore: Update nilup curl URL to include install.sh

docs/_sdk-installation.mdx, docs/js-quickstart.md, docs/nilup.md
This PR updates our nilup install documentation to include a note for security-conscious folk to inspect the install.sh script before piping it to bash to make sure they know we are not trying to hide anything and that we support their possible hesitation around blindly running commands from the internet in their terminals.
=> Update docs to include a note about piping to bash for security-conscious folk

docs/nada.md
Improvement on the section `Build a program` and `nada run`. 
I wanted to clarify the `Build a program` section because it was not totally obvious for me that we need to add a new program into the `.toml` file whenever we want to build it. I know it is described in the docs, but I went directly to the build program section and it took me a bit to understand the answer to my compilation error was described just above.
=> docs: improve the description of nada build and nada run commands

docs/js-client-reference.md
This PR updates user_id and party_id being attributes and not methods in the JS client (updated in https://github.com/NillionNetwork/nillion/pull/1430)
=> fix(JS): update user_id and party_id being attributes and not methods

docs/python-client-reference.md
This PR updates user_id and party_id being attributes and not methods in the Python client
=> fix(Python): update user_id and party_id being attributes and not methods

docs/compute.md, docs/permissions.md, docs/python-quickstart.md, docs/retrieve-secret.md, docs/store-secrets.md, sidebars.js
put all examples into a `examples_and_tutorials/core_concept_*` folder
goes along with Restructure for DevEx - https://github.com/NillionNetwork/nillion-python-starter/pull/21
=> Examples restructure for nillion-python-client files

docs/python-client-reference.md, docs/python-quickstart.md
This PR fixes typos in the python client docs.
=> chore: fix typos in docs

docs/first-steps.md
The link to the discord in first-steps.md was broken. This PR updates it to point to the correct discord URL (https://discord.com/invite/nillionnetwork). This ensures users have access to the relevant information.
=> chore(docs):fix broken/outdated discord link

docs/nillion-devnet.md
When running through the examples, I had something running on that port & it took me a while to figure out what port the `devnet` is actually running on. Would be cool to include this info in `nillion-devnet` CLI's help message as well.
=> Add blurb explaining the `port` that `nillion-devnet` runs on

docs/nada-ai-linear-model.md, docs/nada-ai-neural-network.md, docs/nada-numpy-matrix-multiplication.md
This PR fixes various small typos regarding confusions between `na.output` (which works for any Nada / Nada Numpy / Nada AI datatype) and `result.output` which only does for `NadaArray` and children classes.
=> fix: fixed typos for latest version of Nada AI

docs/python-quickstart.md
The tutorial does not refer to the program name as `secret_addition_complete`, but as `secret_addition`. This place in the code breaks right now if you're following the tutorial.
=> Change name of quickstart program to match tutorial

docusaurus.config.js, package-lock.json, package.json, src/css/custom.css, yarn.lock
Add the feedback feature so community members can provide feedback for any page of the docs.
This will only submit once the url matches docs.nillion.com, so you can't submit feedback for the demo page.
Demo: https://nillion-docs-git-feature-feedback-nillion.vercel.app/
=> add feedback per page feature

docs/_sdk-installation.mdx, docs/quickstart-blind-app.md, docs/quickstart-testnet.md
Was going through the quickstart and found a small discrepnancy. It says to update it to `simple_addition` but the code was just showing the former of  `addition_simple`
Previous:
Current PR:
- It removes the reference + is manual code. If you prefer the `reference showGithubLink` we can think of another method
=> Quickstart Small Fixes 

docusaurus.config.js, sidebars.js, src/css/custom.css
Added in the footer + relegated sidebar links that will free up real estate.
Also gave more free space at the top with the Github / Github Discussions. If we want to put Discussions back, we can. 
Previous:
Current PR
=> Feat: footer

docs/python-quickstart.md, sidebars.js
Hierachy Nitpick to make clients + SDK higher in sidebar hierachy + 
- Small chore to remove unnecessary Tab code at the bottom of Python Quickstart
- Missing instruction to `mv run_my_first_program.py secret_addition.py` for Python Quickstart
Previous:
After:
=> chore: sidebar hierachy + small changes to Python Quickstart

docs/installation.md, docs/showcase.md, src/css/custom.css
Done
- Add info box so developers know to follow the latest Examples
Small Cosmetics:
- Added Divider for windows for legibility.
=> chore: showcase info

docs/nada-lang-programs.md
=> chore: fix nada_fn_max link

docs/aivm.md, docs/first-steps.md, docs/nada-lang-programs.md, docs/nada-numpy-introduction.md, docs/nada.md, docs/python-quickstart.md, docs/start-building.md
This pull request addresses and corrects several typographical errors across the following documentation files:
- **`aivm.md`**
- **`first-steps.md`**
- **`nada-lang-programs.md`**
- **`nada-numpy-introduction.md`**
- **`nada.md`**
- **`python-quickstart.md`**
- **`start-building.md`**
These revisions are aimed at improving the overall clarity and accuracy of the documentation.
=> fix: typos in documentation files

docs/aivm.md, docs/data-wars.md, docs/first-steps.md, docs/glossary.md, docs/nada-libraries.md, docs/welcome.md
This pull request contains changes to improve clarity, correctness and structure.
Description correction:
Corrected "nd" to "and".
Corrected "recieve" to "receive".
Corrected "cipher text" to "ciphertext".
Corrected "syncrhonisation" to "synchronisation".
Corrected "Sci-kit learn" to "Scikit-learn".
Corrected "Applink" to "App link" and much more.
Please review the changes and let me know if any additional changes are needed before merging.
=> Spelling and Grammar Corrections

docs/aivm.md, docs/data-wars.md, docs/nada.md
Fixed few typos for clarity in the documentation. Hope this helps.
=> docs: fix typos

docs/_quickstart-compile-run-test.mdx, docs/installation.md
This pull request corrects minor typos in the following documentation files:  
**Summary of Changes:**  
1. Removed duplicate wording in `_quickstart-compile-run-test.mdx`.  
- Corrected: "add the following to the to the" → "add the following to the".  
2. Adjusted the indefinite article usage in `installation.md`.  
- Corrected: "a Ubuntu terminal" → "an Ubuntu terminal".  
**Files Modified:**  
- `docs/_quickstart-compile-run-test.mdx`  
- `docs/installation.md`  
These fixes improve the clarity and grammatical accuracy of the documentation.
=> Fix typos in quickstart and installation documentation 

docs/build/secret-vault-quickstart.md
Small fix, but important as copying and pasting the examples does not work without it
=> fix: change name of const so it works with example, otherwise broken

docs/build/private-storage/quickstart.md
- In `Step 5`, adds secret sharing to `email` and `phone` fields
- In `Step 7`, adds `blindfold` configuration
- In `Step 8`, adds private data fields
=> docs: add encryption to quickstart guide

docs/build/private-storage/overview.md, docs/build/private-storage/quickstart.md
- Add `$lookup` 
- Fixes typo in Quickstart guide
=> fix: clarify mongodb queries

apispec/nildb/queries.openapi.yaml, docs/api/nildb/get-queries.api.mdx
Description:  
This pull request fixes a typo in the API documentation and OpenAPI spec files, changing "pipline" to the correct spelling "pipeline" in the description of the query execution pipeline. This improves clarity and accuracy in both the OpenAPI YAML and the related MDX documentation. No functional changes were made.
=> Fix Typo: Correct "pipline" to "pipeline" in API Documentation
