NillionNetwork/nillion-docs

- docs/nada.md
- docs/nilup.md
- docs/sdk-instrumentation.md
@oceans404 the instrumentation documentation is not linked anywhere, please feel free to link it whenever you need to. It will probably be good to have it linked in the quickstart when we recommend activating it.
> Add nilup, nada and instrumentation doc

- docs/sdk-instrumentation.md
Minor fix in data collection text from legal
> Minor fix in data collection text from legal

- docs/js-quickstart.md
reported in NillionNetwork/discussions#32
> docs: fix venv script call in JS Quickstart

- docs/first-steps.md
Some minor changes to first steps page
> minor tweaks

- docs/first-steps.md
- docs/hacker-house.md
- docs/hacker_house_windows.md
> Hacker house

- docs/hacker-house-goa-windows.md
- docs/hacker-house-goa.md
> update discord links

- docs/hacker-house-goa-windows.md
Very small change, merging without review to get it there ASAP
> remove colab for windows

- docusaurus.config.js
Verify ownership of docs site for Google Cloud
> chore: add google-site-verification tag

- docs/_sdk-installation.mdx
- docs/installation.md
- docs/limitations.md
- sidebars.js
https://nillion-docs-git-feature-windows-setup-nillion.vercel.app/installation#windows-guide
> added windows wsl setup instructions

- docs/_nada-venv-setup.mdx
- docs/nada-ai-linear-model.md
- docs/nada-ai-neural-network.md
- docs/nada-numpy-introduction.md
- docs/nada.md
- docs/python-client.md
- docs/python-quickstart.md
to pip install so that it always checks for and pulls the latest
> adding --upgrade flag 

- docs/nada-ai-introduction.md
- docs/what-is-nillion.md
See new section: https://nillion-docs-git-ai-limitations-nillion.vercel.app/nada-ai-introduction#llms-and-nada-ai
> add note about llms and nada ai

- package.json
- src/theme/SearchBar/index.js
- yarn.lock
The AI assistant and co-pilot is trained on all existing Nillion Network resources (source code, docs website, etc) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building projects on Nillion, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity/Python coding co-pilot.
Ask Cookbook AI could also access context from thousands of data sources indexed by Cookbook.dev in addition to Nillion-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.
https://nillion-docs-cookbook.vercel.app/
> feat: Cookbook Onboard integration

- docs/nada-by-example/linear-scan.md
- sidebars.js
demo: https://nillion-docs-git-feat-linear-scan-nillion.vercel.app/nada-by-example/linear-scan
> add linear scan example to nada-by-example

- docs/_data-types-table.mdx
- docs/nada-by-example/literal-data-type.md
- docs/nada-by-example/public-data-type.md
- docs/nada-by-example/secret-data-type.md
- docs/nada-lang-types.md
> Document Boolean types

- docs/nada-by-example/cardio-risk.md
- sidebars.js
demo: https://nillion-docs-git-ex-cardio-risk-nillion.vercel.app/nada-by-example/cardio-risk
> add cardio risk example

- docs/_sdk-installation.mdx
> chore: small updates for nilup -v

- docs/installation.md
Add Tabs/TabItems to the Mac / Linux + Windows Guide
Outcome
- Less Scrolling
> chore: separate mac and windows in tabs

- docusaurus.config.js
Looking to add better doc experience and tracking with [Safary](https://safary.club/). 
Safary is a privacy preserving, more web3 native analytics tool. 
- No cookies
- No personal data collected.
-  tag tracking
- GDPR compliant
> Feat: init safary

- docs/nada.md
- src/components/Networks/network-info.js
- Update nada docs to add benchmark and metrics tools 
- Metrics: https://nillion-docs-git-feat-tool-updates-nillion.vercel.app/nada#run-and-get-metrics
- Benchmark summary: https://nillion-docs-git-feat-tool-updates-nillion.vercel.app/nada#get-a-benchmark-summary-for-a-program
- Update network configuration page to point to new GRPC https://nillion-docs-git-feat-tool-updates-nillion.vercel.app/network-configuration
> feat: nada tooling updates, grpc url update for 0.6.0

- package-lock.json
- yarn.lock
Needed to update respective files
- package-lock.json
- yarn.lock
As this styled-components error (coming from CookBook) has conflicts with the older package files + produces error
Expected Behaviour
- No error 
- Fixed in this PR
Current Error
> Chore: fix older styled components conflicts

- .gitignore
- docs/glossary.md
- docs/nada-execution-plan.md
- docs/nada-metrics.md
- docs/nada.md
- sidebars.js
This updates the nada metrics sections according to [Nada Metrics](https://github.com/orgs/NillionNetwork/projects/12?pane=issue&itemId=80081522&issue=NillionNetwork%7Cnada-lang%7C8).
> chore: Update nada metric sections

- docs/aivm-supported-models.md
- docs/aivm.md
- sidebars.js
This PR includes mutiple small fixes to the AIVM docs.
> fix: AIVM Docs

- docs/aivm.md
> chore: WSL

- docs/aivm.md
> chore: add collab + git clone

- docusaurus.config.js
> chore: update scripts

- docs/network-configuration.md
- src/components/Networks/TestnetEnv.js
- src/components/Networks/index.js
- src/components/Networks/network-info-photon2.js
Updates to Network table for 0.6.0 and 0.7.0
@jwolski2 if you could double check the [config](https://github.com/NillionNetwork/nillion-docs/pull/136/files#diff-3252fbd2dd0c85dc5fffd53028e9623c28becaa30c5ff6656e2389c15df40f6f) here. thanks!
> chore: added new network configs

- docs/js-client-hooks-compute.md
- docs/js-client.md
- docs/quickstart-blind-app.md
- docs/quickstart-testnet.md
- Updated Quickstart
- Minor network changes for JS Usage
> Update for latest CNA / JS Client

- docs/build/secretLLM/access.md
- docs/build/secretLLM/overview.md
- docs/network.md
- docs/quickstart.mdx
- sidebar-build.js
- src/utils/FeatureCards.js
> add network config at the build level

- docs/_testnet_block_explorers.mdx
- docs/build/secretSigner/setup.md
- docs/guide-nillion-wallet.md
- docs/guide-sending-nil.md
- docs/guide-testnet-faucet.md
- docs/quickstart-testnet.md
- docs/testnet-guides.md
- sidebar-community.js
Demo: https://nillion-docs-git-nilchain-guides-nillion.vercel.app/community-and-support
> update nilChain Guides

- docs/what-is-nillion.md
- sidebar-nilvm.js
> chore: add to

- docs/build/secretVault-secretDataAnalytics/create-schema.md
Better readability / separate concerns
Previous:
Now:
> chore: refactor to tabs for create-schema

- docs/build/ai-assisted-workflow/llm-summary-12k.mdx
- docs/build/ai-assisted-workflow/llm-summary-6k.mdx
- docs/build/private-llms/overview.md
- docs/build/private-llms/usage.mdx
> docs: updates LLM's offered

- docs/build/ai-assisted-workflow.md
- docs/build/quickstart.mdx
- docusaurus.config.js
- package-lock.json
- package.json
- sidebar-build.js
- src/css/custom.css
- static/llm.txt
Add button to open Nillion Builder LLM + umami tracking
Remove "Feedback" since we are over the pushfeedback free trial
> add Nillion Builder LLM to docs, remove feedback
